"""Exact user-specified pediatric cohort. Does not delete archives.
Run from task workspace: python outputs/analyze_specified_pediatric_35.py
Requires the full-cohort-results.json generated by analyze_thickness.py.
"""
import sys,json,csv
from pathlib import Path
sys.path.insert(0,str(Path('work/stats_deps').resolve()))
sys.path.insert(0,str(Path('work/pediatric_deps').resolve()))
import numpy as np
from scipy import stats

out=Path('outputs')
base=json.loads((out/'full-cohort-results.json').read_text())
subjects=base['subjects']
dl = {"sub-047EPKL"+s for s in "011005 011012 011041 011047 011049 011051 011056 011058 011059 011060 011063 011068 012014 012015 012017 012069 012071".split()}
td = {"sub-047EPKL"+s for s in "014007 014010 014024 014026 014029 014031 014036 014037 014038 014040 014045 014048 014050 014052 014054 014062 014066 014067".split()}
assert len(dl)==17 and len(td)==18 and not dl & td
requested=dl|td
kept=[r.copy() for r in subjects if r['dataset']=='ds003126' and r['participant_id'] in requested]
assert {r['participant_id'] for r in kept}==requested and len(kept)==35
assert all(r['group']==('dyslexia' if r['participant_id'] in dl else 'control') for r in kept)
excluded=[dict(dataset=r['dataset'],participant_id=r['participant_id'],group=r['group'],reason='Not in user-specified 35-subject list; no outlier status inferred') for r in subjects if r['dataset']=='ds003126' and r['participant_id'] not in requested]
assert len(excluded)==6
base['results']=[r for r in base['results'] if r['dataset']=='ds003126']
results=[];welch=[]; rng=np.random.default_rng(20260919)
for template in base['results']:
    d,f=template['dataset'],template['measurement']
    x=np.array([r[f] for r in kept if r['dataset']==d and r['group']=='dyslexia'])
    y=np.array([r[f] for r in kept if r['dataset']==d and r['group']=='control'])
    assert (len(x),len(y))==((17,18) if d=='ds003126' else (32,35))
    u=stats.mannwhitneyu(x,y,alternative='two-sided',method='asymptotic',use_continuity=True)
    assert u.statistic==np.sum(x[:,None]>y)+.5*np.sum(x[:,None]==y)
    bx=rng.choice(x,(10000,len(x)));by=rng.choice(y,(10000,len(y)))
    bs=stats.mannwhitneyu(bx,by,axis=1,method='asymptotic').statistic
    ci=np.quantile(2*bs/(len(x)*len(y))-1,[.025,.975])
    r=dict(dataset=d,cohort=template['cohort'],measurement=f,units=template['units'],
        n_dyslexia=len(x),n_control=len(y),U_dyslexia=float(u.statistic),p_two_sided=float(u.pvalue),
        rank_biserial=float(2*u.statistic/(len(x)*len(y))-1),rank_biserial_CI_low=float(ci[0]),rank_biserial_CI_high=float(ci[1]))
    for group,a in [('dyslexia',x),('control',y)]:
        q1,med,q3=np.quantile(a,[.25,.5,.75],method='linear')
        r.update({group+'_median':float(med),group+'_Q1':float(q1),group+'_Q3':float(q3),group+'_IQR':float(q3-q1)})
    results.append(r)
    if f=='network_ratio':
        t=stats.ttest_ind(x,y,equal_var=False);ci_t=t.confidence_interval(.95)
        welch.append(dict(dataset=d,n_dyslexia=len(x),n_control=len(y),t=float(t.statistic),df=float(t.df),p_two_sided=float(t.pvalue),mean_difference_dyslexia_minus_control=float(x.mean()-y.mean()),CI_low=float(ci_t.low),CI_high=float(ci_t.high)))
def adjust(rows,key):
    order=sorted(range(len(rows)),key=lambda i:rows[i]['p_two_sided']);running=0
    for rank,i in enumerate(order):
        running=max(running,min(1.,(len(rows)-rank)*rows[i]['p_two_sided']));rows[i][key]=running
adjust(results,'p_Holm_4_tests')
for name,rows in [('specified-pediatric-35-comparisons.csv',results),('specified-pediatric-35-subjects.csv',kept),('specified-pediatric-35-not-included.csv',excluded),('specified-pediatric-35-welch-tests.csv',welch)]:
    with open(out/name,'w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
payload={**base,'results':results,'subjects':kept,'welch':welch,'statistical_exclusions':excluded,
 'selection_note':'Exact 17 DL and 18 TD IDs supplied by user. No ratio-based exclusions. Selection provenance beyond the provided list has not been established. Adult results untouched.'}
(out/'specified-pediatric-35-results.json').write_text(json.dumps(payload,indent=2))
print(json.dumps({'excluded':excluded,'results':[{k:r[k] for k in ['dataset','measurement','U_dyslexia','p_two_sided','rank_biserial']} for r in results]},indent=2))

